apiVersion: apps/v1
kind: Deployment
metadata:
  name: datacatalogapi
  labels:
    app: datacatalog
spec:
  replicas: 1
  selector:
    matchLabels:
      service: datacatalogapi
  template:
    metadata:
      labels:
        app: datacatalog
        service: datacatalogapi
    spec:
      containers:
        - name: datacatalogapi
          image: <container-registry>/<image-name>:<tag>
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: IdentityProviderUrl
              valueFrom:
                configMapKeyRef:
                    name: environmentconfig
                    key: IdentityProviderUrl
            - name: IdentityProvider
              valueFrom:
                configMapKeyRef:
                    name: environmentconfig
                    key: IdentityProvider
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                    name: environmentconfig
                    key: AspNetCore_Environment
---
apiVersion: v1
kind: Service
metadata:
  name: datacatalogapi
  labels:
    app: datacatalog
    service: datacatalogapi
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: datacatalogapi